spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token
    client:
      client-id: web
      client-secret: webpass